### ISSUE TITLE
rename variables to fit the python naming convention

### ISSUE THREAD

**Issue by s81320** [s81320/reversi#2]
change from setStone to set_stone
change all (only a few) variable names that are still in German.

Should be fast in IntelliJ.

**Comment by grossamos** [comment]
Seeing how there seem to be quite a small amount of people willing to work on the issues of the project, I'd be glad to help on this issue. As quite an avid python programmer (and native german speaker) please note if there is anything else I could help you with.

**Comment by s81320** [comment]
Thank you for offering help! I did not read read this till a couple of days ago in Feb... so by now it is done :-)
