### ISSUE TITLE
get tkinter running

### ISSUE THREAD

**Issue by s81320** [s81320/reversi#4]
at the moment my python environment (on my laptop) does not execute tkinter.

**Comment by OlesTurchyn** [comment]
Before you start using Tkinter in your python environment, you need to make sure tkinter is installed. If you are using windows, go to your command prompt and enter `pip install tkinter`. This should work if you are using a version of Python 3.0.

If this does not work, look for some tutorials on youtube. I'm sure you will find something there.
Here is a tutorial I recommend: https://www.youtube.com/watch?v=A2FNzpBx4vM

**Comment by s81320** [comment]
Thank you for your comment!
I will close the issue. Since this project has to be handed in soon, I will not use tinter for this project at the moment.
